# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration.html

[font]
family = "Cascadia Code"
size = 16

[servers.soju]
nickname = "hskim"
server = "irc.dilluti0n.com"

[servers.soju.sasl.plain]
username = "hskim"
password_command = "pass show hskim/misc/soju | head -n1"
